---
abstract: 'Perl extension for dispaying bars in the terminal'
author:
  - 'Gil Gonçalves <lurst@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-Vspark
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Term::Vspark:
    file: lib/Term/Vspark.pm
    version: 0.07
requires:
  Carp: 0
  POSIX: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/LuRsT/term-vspark/issues
  homepage: https://metacpan.org/release/Term-Vspark
  repository: git://github.com/LuRsT/term-vspark.git
version: 0.07
